@startuml
hide empty description
state "Decision" as decision <<choice>>
[*] --> PendingRequest: requestCollectionLoc()
PendingRequest --> decision
decision --> RejectedRequest: LO rejects\n the Request
decision --> OpenLoc: LO accepts\n the Request
OpenLoc --> VoidedCollectionLoc: LO voids\n the LOC
OpenLoc --> ClosedCollectionLoc: LO closes\n the LOC
ClosedCollectionLoc --> VoidedCollectionLoc: LO voids\n the LOC
VoidedCollectionLoc --> [*]
OpenLoc --> OpenLoc: addMetadata(),\n addFile(),\n deleteMetadata(),\n deleteFile(),\n requestSof(),\n getCollectionItem()
ClosedCollectionLoc --> ClosedCollectionLoc: addCollectionItem(),\n uploadCollectionItemFile(),\n requestSof()
@enduml
